### ISSUE TITLE
Bug: using form button selects twice per click

### ISSUE THREAD

**Issue by renemarc** [InputObject2/random-picker#1]
## Issue
Clicking on the `Select Random Item` form button triggers the random selection twice, leading to generally a 50% Selection Percentage for 2 items on the first go, with a Selection Count of 1 each. Each button click afterwards leads to 2 triggers again.

Using `CTRL+G` instead of clicking the form button works as expected, trigering a single selection event at a time.

![image](https://github.com/InputObject2/random-picker/assets/13276793/789e0c3d-fafc-4169-9fa3-8a9979da37c0)

## Expected behavior
Clicking the form button should only trigger the form once per click, akin to using `CTRL+G`. The first click on the button should therefore hightlight a single entry with 100%. Further clicks should also just trigger the selection once per click, not twice.

![image](https://github.com/InputObject2/random-picker/assets/13276793/1e6f2993-8dc2-4cbb-b233-4ef6bfb0a180)

## Environment
Tested using `docker.io/inputobject2/random-picker:latest` and on both Firefox 123 and Edge 122.

**Comment by InputObject2** [comment]
Thanks for the details! 

Looks like when I added the ctrl+g shortcut in 3bafa1b I forgot to remove the code for the count in the button instead of calling the function.
